In [2]:
import numpy
x = numpy.random.randint(0,10,(3,3,3))
y = numpy.random.randint(0,10,(3,3,3))
x,y,x+y,x.shape,x.ndim,x.dtype,x.size

(array([[[6, 4, 5],
         [5, 4, 5],
         [7, 0, 5]],
 
        [[6, 0, 1],
         [0, 6, 1],
         [2, 2, 7]],
 
        [[1, 9, 0],
         [7, 7, 5],
         [3, 4, 2]]], dtype=int32),
 array([[[0, 2, 2],
         [0, 1, 4],
         [0, 5, 1]],
 
        [[4, 4, 8],
         [0, 2, 1],
         [5, 0, 5]],
 
        [[1, 7, 9],
         [1, 6, 1],
         [5, 7, 4]]], dtype=int32),
 array([[[ 6,  6,  7],
         [ 5,  5,  9],
         [ 7,  5,  6]],
 
        [[10,  4,  9],
         [ 0,  8,  2],
         [ 7,  2, 12]],
 
        [[ 2, 16,  9],
         [ 8, 13,  6],
         [ 8, 11,  6]]], dtype=int32),
 (3, 3, 3),
 3,
 dtype('int32'),
 27)