In [ ]:
import numpy as np

### 1、Numpy的ndarray的一维，二维的reshape互相变换

In [ ]:
a = np.arange(1,5)
print(a)
b = a[np.newaxis, :]
print(b)
c = b.reshape(-1,)
c

[1 2 3 4]
[[1 2 3 4]]


array([1, 2, 3, 4])

### 2、掌握numpy的数据类型，练习数组和数的运算，数组和数组的运算，理解数组的轴

In [ ]:
a = np.arange(1,5)
print(a)
print('-'*20)
print((a*10+1)/2)

[1 2 3 4]
--------------------
[ 5.5 10.5 15.5 20.5]


array([1, 2, 3, 4])

### 3、使用数组的索引和切片，掌握数组数值修改

In [10]:
a = np.random.randint(0, 10, size=(2, 2, 4))
print(a,'\n','-'*20)
print(a[[0,1],:,1:])


[[[8 6 9 0]
  [1 6 6 2]]

 [[0 3 8 9]
  [7 8 6 4]]] 
 --------------------
[[[6 9 0]
  [6 6 2]]

 [[3 8 9]
  [8 6 4]]]


### 4、完成数组的添加练习

In [30]:
a = np.arange(0,5).reshape(1,5)
print(a)
print(np.append(a,np.array([5,6,7])))
# 调试：修正 np.insert 的插入值形状，使其与 a 的列数一致
print(np.insert(a, 1, np.arange(5,10), axis=0))


[[0 1 2 3 4]]
[0 1 2 3 4 5 6 7]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 5、完成数组的连接，堆叠

In [ ]:
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print(np.concatenate((a,b)))
print(np.concatenate((a,b), axis=1))
print('-'*20)
a = np.arange(0,5)
b = np.arange(5,10)
print(np.stack((a,b)))
print(np.stack((a,b), axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
--------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 6、np二维数组转置练习，轴滚动练习